- hosts: all
  become: yes
  tasks: 
  - name: Install Apache (HTTPD)
    ansible.builtin.dnf:
      name: 
        - httpd
      state: present
  
  - name: Start and enable service httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes

  - name: Add the users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop:
      - jenny
      - rose
      - jisoo
      - lisa

