- hosts: vm1
  become: yes
  tasks:
  - name: Install apache
    ansible.builtin.apt:
      name: tree
      state: absent
      update_cache: yes
    notify: [Restart service apache2, Create user brad]
  
  handlers:
  - name: Restart service apache2
    ansible.builtin.service:
      name: apache2
      state: restarted

  - name: Create user brad
    ansible.builtin.user:
      name: brad