- hosts: all
  become: yes
  vars:
    hello: kaizen
  tasks:
  - name: Add the user
    ansible.builtin.user:
      name: tim
    when: hello == "kaizen"
  - name: Add the user
    ansible.builtin.user:
      name: ann
    when: hello == "world"
  - name: Add the user
    ansible.builtin.user:
      name: eric
    when: hello == "file"